ALTER TABLE agencies 
ADD COLUMN IF NOT EXISTS is_micro BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_icp BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_enterprise BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_captive BOOLEAN DEFAULT FALSE;
